apiVersion: v1
entries:
  vm-template:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-02T14:05:16.829673324Z"
    description: A Helm chart for VM deployment on multiple cloud providers
    digest: 90d6ab9db0ed0d4cee98e14d06df412afd2c2ef30cfe919c17cc2d2b5a7910d9
    name: vm-template
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/vm-template-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-02T14:05:16.829258708Z"
