apiVersion: v1
entries:
  vm-template:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-03T15:15:24.72740651Z"
    description: A Helm chart for VM deployment on multiple cloud providers
    digest: a8bebb1ed0751784060faba5eb700a6d7e0630457dea9f1620b55c593cf6660f
    name: vm-template
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/vm-template-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-03T15:15:24.726982318Z"
