apiVersion: v1
entries:
  vm-template:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-01T17:42:18.00892798Z"
    description: A Helm chart for VM deployment on multiple cloud providers
    digest: 4d8c7eaafcac181fd82cd5ee5cd8bc2b0514cc9a8b9eaa72231a953c56d96dde
    name: vm-template
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/vm-template-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-01T17:42:18.008416425Z"
