apiVersion: v1
entries:
  mlflow-cratedb:
  - apiVersion: v2
    appVersion: 2.14.0
    created: "2025-01-28T17:27:49.498924273Z"
    description: A Helm chart for MLflow-CrateDB adapter
    digest: 97745d247d0d3cfee0d51a33eb9c29e97a84f99898906dae45ca4eb0ec65f009
    name: mlflow-cratedb
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/mlflow-cratedb-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 2.14.0
    created: "2025-01-27T17:55:03.807839825Z"
    description: A Helm chart for MLflow-CrateDB adapter
    digest: b46d54f93c4be45aced52498557d9df3d9cff773209391b58f041980cd4df6fb
    name: mlflow-cratedb
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/mlflow-cratedb-0.1.0.tgz
    version: 0.1.0
  opa:
  - apiVersion: v2
    appVersion: 0.70.0
    created: "2025-01-29T23:09:45.557367497Z"
    description: A Helm chart for Open Policy Agent
    digest: 5aa7a5253553f92cac3ef32f9023e65e5befa48b870cbee5d1dd309c2ec34fd2
    name: opa
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/opa-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.70.0
    created: "2025-01-29T17:04:10.379500316Z"
    description: A Helm chart for Open Policy Agent
    digest: 3473e6016fc288a4a2b18db88cb9ae7a2cb4d51fc290e03eab474fa8aac18764
    name: opa
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/opa-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.70.0
    created: "2025-01-29T14:39:27.618356894Z"
    description: A Helm chart for Open Policy Agent
    digest: 82fbaf3559676f4bfb68fb018c9910b4d76814bab45a3d5aaf0121c6d6d91b6d
    name: opa
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/opa-0.1.0.tgz
    version: 0.1.0
  vm-template:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2024-12-12T13:36:55.745310751Z"
    description: A Helm chart for VM deployment on multiple cloud providers
    digest: 53bea94d15fb92830ec334fbe3fb2b85e1be95abd567f0ee527ad8dac74197b5
    name: vm-template
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/vm-template-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2024-12-11T14:50:17.185906559Z"
    description: A Helm chart for VM deployment on multiple cloud providers
    digest: 3ee7869f51de839bf8fdf5318b10ac393199414c6e712a193b9084101ec446f9
    name: vm-template
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/vm-template-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-05T13:37:34.013022941Z"
    description: A Helm chart for VM deployment on multiple cloud providers
    digest: 235b626509421dc482f99d38cc861473c38ce8167dd5dbcab4ca4dd71b2df983
    name: vm-template
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/vm-template-1.0.0.tgz
    version: 1.0.0
generated: "2025-01-29T23:09:45.556625633Z"
