apiVersion: v1
entries:
  vm-template:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-03T13:12:54.100031691Z"
    description: A Helm chart for VM deployment on multiple cloud providers
    digest: d2559187644261693b1b3727c04413655c7a25398c7c5b83330320559f3ccdbe
    name: vm-template
    type: application
    urls:
    - https://vicentinileonardo.github.io/helm-charts/charts/vm-template-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-03T13:12:54.099161119Z"
